namespace InstagramTokenExample
{
    using System.Collections.Generic;

    class Program
    {
        static void Main(string[] args)
        {
            // Provide token generated by instagram test user
            string token = @"IGQVXXXXXXXXXXXXXXXX";

            var service = new SocialFeedService();
            IEnumerable<InstagramMediaContent> result = service.GetInstagramContents(token);

            // To Refresh the Instagram Token
            string tokenExpiry = service.RefreshToken(token);
        }
    }
}